filetype off
call pathogen#runtime_append_all_bundles()

" All system-wide defaults are set in $VIMRUNTIME/debian.vim (usually just
" /usr/share/vim/vimcurrent/debian.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vim/vimrc), since debian.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing debian.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
"runtime! debian.vim

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numeros
" options, so any other options should be set AFTER setting 'compatible'.
"set compatible

" Vim5 and later versions support syntax highlighting. Uncommenting the
" following enables syntax highlighting by default.
if has("syntax")
  syntax on
endif

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
"set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
  filetype plugin indent on
endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
set showmatch		" Show matching brackets.
set ignorecase		" Do case insensitive matching
set smartcase		" Do smart case matching
set incsearch		" Incremental search
set showmatch
set hlsearch
set autowrite		" Automatically save before commands like :next and :make
set hidden             " Hide buffers when they are abandoned
set mouse=v		" Enable mouse usage (all modes)

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

set softtabstop=4
set expandtab
set tabstop=4
set shiftwidth=4
set nu
set foldmethod=indent

"设置会话，添加还原Vim窗口大小的功能
set sessionoptions+=resize

"Use the tab key match bracket pairs. It's a hell of a lot easier to type <tab> than <%>
nnoremap <tab> %
vnoremap <tab> %

"These lines manage my line wrapping settings and also show a colored column
"at 85 characters
set wrap
set textwidth=79
set formatoptions=qrn1
set colorcolumn=85

"Makes j and k work the way you expect instead of working in some archaic
"'movement by file line instead of screen line' fashion
nnoremap j gj
nnoremap k gk

"Quicker Escaping, note conflict when type 'jj' in insert mode
inoremap jj <ESC>

"A few options that just make things better
set encoding=utf-8
set scrolloff=3
set autoindent
set showmode
set visualbell
set showmode
set showcmd
set wildmenu
set wildmode=list:longest
set cursorline
set ttyfast
set ruler
set laststatus=2
"当 VIM 工作在 Unicode 状态时，遇到这些宽度不明的字符时，默认使用窄字符，这会导致
"中文的破折号“——”非常短，五角星★等符号只能显示一半。因此，我们需要设置 ambiwidth=double 来解决这个问题。
set ambiwidth=double

"search with -
"eg. hello-world as a whole word
" set iskeyword+=-

"new in Vim 7.3
set relativenumber

"Shortcut for NERDTree plugin
map <F2> :NERDTreeToggle<CR>

"Change the <leader> key, <,> is easier to type than <\>
let mapleader = ","

"Key mapping for zen coding
let g:user_zen_expandabbr_key = '<c-e>'

"By default Vim doesn't fold Javascript files,but you can add some
"basic,perfectly serviceable folding with these two lines in your .vimrc
au FileType javascript setlocal foldmethod=marker
au FileType javascript setlocal foldmarker={,}

" CoffeeScript config
" watch mode show in vertical window
let coffee_compile_vert = 1
" See :help expand()
" Compile *.coffee to ../*.js
au BufWritePost *.coffee silent execute 'CoffeeMake! -o '.expand('<afile>:p:h').'/../'

" less
au BufNewFile,BufRead *.less set filetype=less
autocmd BufWritePost,FileWritePost *.less !lessc <afile> <afile>:p:h:h/<afile>:t:r.css

syntax enable
set background=light
colorscheme solarized

" Change cursor shape in different modes for the Gnome-Terminal(ver 2.26)
if has("autocmd")
  au InsertEnter * silent execute "!gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/cursor_shape ibeam"
  au InsertLeave * silent execute "!gconftool-2 --type string --set /apps/gnome-terminal/profiles/Default/cursor_shape block"
endif
